devices: eno1
externalIPs:
  enabled: true
k8sClientRateLimit:
  burst: 100
  qps: 50
k8sServiceHost: 192.168.1.207
k8sServicePort: 6443
kubeProxyReplacement: true
l2announcements:
  enabled: true
operator:
  replicas: 1
socketLB:
  hostNamespaceOnly: true
envoy:
  enabled: false
