apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nuc01-apps
  namespace: argocd
spec:
  goTemplate: true
  applyNestedSelectors: true
  generators:
    - matrix:
        generators:
          - git:
              files:
                - path: apps/apps.yaml
              repoURL: https://github.com/mikejoh/k8s-applications.git
              revision: main
          - list:
              elements: []
              elementsYaml: "{{ .apps | toJson }}"
    - clusters: {}
  syncPolicy:
    preserveResourcesOnDeletion: true
  ignoreApplicationDifferences:
    - jsonPointers:
      - /spec/source/targetRevision
    - jqPathExpressions:
      - .spec.sources[] | .targetRevision
  template:
    metadata:
      name: "{{ .app }}"
    spec:
      destination:
        namespace: "{{ if .namespace }}{{ .namespace }}{{ else }}{{ .app }}{{ end }}"
        server: https://kubernetes.default.svc
      project: default
      source:
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
        path: apps/charts/{{ .app }}
        repoURL: https://github.com/mikejoh/k8s-applications.git
        targetRevision: "{{ .revision }}"
  templatePatch: |
    spec:
      syncPolicy:
        syncOptions:
          - FailOnSharedResource=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        {{- range $opt := .syncOptions }}
          - {{ $opt }}
        {{- end }}
